name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    concurrency:
      group: lint
    steps:
    - uses: actions/checkout@v4
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
    - run: poetry install --no-root
    - run: poetry run task test
    - run: poetry run task lint

  formatter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    concurrency:
      group: formatter
    needs: build  # Ustalamy, że formatowanie uruchamia się po zakończeniu joba 'build'
    steps:
    - uses: actions/checkout@v4
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
    - run: poetry install --no-root
    - run: poetry run task formatter

  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    concurrency:
      group: security
    needs: build  # Ustalamy, że bezpieczeństwo uruchamia się po zakończeniu joba 'build'
    steps:
    - uses: actions/checkout@v4
    - name: Cache build venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
    - run: poetry install --no-root
    - run: poetry run task security
